sudo: true
language: php
env:
  global:
    - APP_ENV=testing
    - APP_KEY=base64:B1PnRwGSyTSWM+qFnnSdMP6r0as4+jtlSu9OS5x3Abs=
    - DB_CONNECTION=mysql
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_DATABASE=travis
    - DB_USERNAME=root
    - DB_PASSWORD=""
php:
  - nightly
  - 7.2
  - 7.1
  - 7.0
before_install:
  - bash .travis.install-mysql-5.7.sh
install:
  - composer install
script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
